services:
    larpake_pg_production:
        container_name: larpake_pg_production
        platform: linux/amd64
        image: postgres:17.3-bookworm
        env_file: .env
        environment:
            - POSTGRES_USER:${POSTGRES_ADMIN_USERNAME}
            - POSTGRES_PASSWORD:${POSTGRES_ADMIN_PASSWORD}
            - POSTGRES_DB:${POSTGRES_NAME}
        volumes:
            - larpake-pg-data:/var/lib/postgresql/data/
        ports:
            - "127.0.0.1:5501:5432"
        networks:
            - weba-network

    larpake_api_production:
        container_name: larpake_api_production
        build:
            dockerfile: api.Dockerfile
        ports:
            - "127.0.0.1:5502:8080"
        networks:
            - weba-network

volumes:
    larpake-pg-data:

networks:
    weba-network:
        external: true
